### ISSUE TITLE
Error: Could not find or load main class com.cooltrickshome.helper.RunProgramDex

### ISSUE THREAD

**Issue by ptx0** [csanuragjain/APKRepatcher#1]
Error: Could not find or load main class com.cooltrickshome.helper.RunProgramDex
Encountered errors/warnings while running this program

**Comment by csanuragjain** [comment]
Please check if you have a folder named
com\cooltrickshome\helper\RunProgramDex

**Comment by YouROK** [comment]
I have the same error on the system apk setting.apk and the directory with the files exists (com\cooltrickshome\helper\RunProgramDex)

[Settings.apk.tar.gz](https://github.com/csanuragjain/APKRepatcher/files/1649715/Settings.apk.tar.gz)

**Comment by oluque002** [comment]
Hi, I had the same issue, and I solved it changing ";" for ":" in the source " APKRepatcher/src/test/java/com/cooltrickshome/Utility.java", line 317:19. I attach the git diff file.
[issue_solved.diff.zip](https://github.com/csanuragjain/APKRepatcher/files/1657753/issue_solved.diff.zip)

**Comment by csanuragjain** [comment]
thanks :)

**Comment by CapacitorSet** [comment]
In general, to run the code on Linux you have to change all occurrences of `.;` to `.:`, it seems.

**Comment by CapacitorSet** [comment]
Fixed here, along with fixing the compilation process: https://github.com/CapacitorSet/APKRepatcher

**Comment by csanuragjain** [comment]
Updated project to use File.pathSeparator to resolve the problem
