### ISSUE TITLE
[Request] Allows to change font

### ISSUE THREAD

**Issue by ANR2ME** [csanuragjain/APKRepatcher#10]
Hi, since most of the outputs are source code, it might be better to use fonts like "Courier New" or Courier when editing/viewing those source code, since it's easier to looked at because each character have the same width and it's easier to differentiate between uppercase I, lowercase L, and number 1.

So i was hoping to be able to change the font.

Thanks in advance.

**Comment by csanuragjain** [comment]
Changed font to Monospaced
