### ISSUE TITLE
Javac problem

### ISSUE THREAD

**Issue by tdaron** [csanuragjain/APKRepatcher#16]
When compiling , the javac command is :

`javac -cp .:/home/XXX/Documents/APKRepatcher/Projects/XXX.apk/modifiedJar/;/home/XXX/Documents/APKRepatcher/APKRepatcher_lib/userLibrary/* XXX.java `

BUT there is a ';' which must be replaced by a ":" otherwise the order is not good

**Comment by manciuszz** [comment]
How is this an _**APKRepatcher**_ problem? All I see, just you messing up the class paths in **_YOUR_ CUSTOM CONFIGURATION**.
 https://docs.oracle.com/javase/7/docs/technotes/tools/windows/classpath.html
