### ISSUE TITLE
Cannot run javac

### ISSUE THREAD

**Issue by Matt0000** [csanuragjain/APKRepatcher#3]
I cannot seem to figure out what this error means when I try to recompile/save the apk.

Could this please be looked into? Here is a picture https://i.imgur.com/2rf18ZX.png

**Comment by csanuragjain** [comment]
@Matt0000 Seems like you have not defined javac in your system variables.

Please add it https://docs.oracle.com/javase/tutorial/essential/environment/paths.html

**Comment by csanuragjain** [comment]
Let me know if you still get the problem
